## Bitboard für Onitama



```
Namenskonventionen
bitboard = Zahl, die ein bitboard darstellt
k = int, 0 - 24, Index auf dem 5x5 bitboard Feld
a = Liste mit bitboards
x = einzelnes bitboard, b1, b2 einzelne bitboards
e = einzelnes bitboard mit nur einer Position
na = numpy Array
st = state 

precalculated dicts:


pos2bb = getPos2bb(), pos2bb[k] = e
posNamen = getPosNamen()  dict das zu einem e den boardnamen zurückgibt
```
 

In [2]:
import numpy as np

In [3]:
def bz(na):
    ''' na : numpy-array 5x5 oder 5x7
        returns: int, bitboard von a
    '''
    return int(''.join([str(x) for x in na.flatten()]),2)

def test_bz():
    na = np.zeros((5, 5), dtype = int)
    na[4,3] = 1
    print(bz(na))   # expect 2
    
test_bz()

2


In [4]:
def board(x):
    ''' x: bitboard einer 5 x 5 boards
        returns: 5 x 5 numpy-Array
    '''
    bs = bin(x)[2:]
    bs = bs.rjust(25,'0')
    bs = bs[len(bs)-25:]
    i, j = 0, 0
    tmp = np.zeros((5, 5), dtype = int)
    for c in bs:
        tmp[i,j] = int(c)
        j = j+1
        if j > 4:
            j = 0
            i = i+1
    return tmp

def test_board():
    print(board(10))
    
test_board()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 0]]


In [5]:
def board7(x):
    ''' k: bitboard einer 5 x 7 boards
        returns: 5 x 7 numpy-Array
    '''
    bs = bin(x)[2:]
    bs = bs.rjust(35,'0')
    bs = bs[len(bs)-35:]
    i, j = 0, 0
    tmp = np.zeros((5, 7), dtype = int)
    for c in bs:
        tmp[i,j] = int(c)
        j = j+1
        if j > 6:
            j = 0
            i = i+1
    return tmp

def test_board7():
    print(board7(10))
    
test_board7()

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0]]


In [6]:
def nw(k,id):
    '''
    k: int, 0 - 24, PositionsIndex
    id: int, 0 -15,  Kartenid
    returns: Liste mit den Nachfolge-bitboards bei Spielen der Karte id an Position k für Spieler weiß
    '''
    zeile = k // 5
    spalte = k % 5
    a = np.zeros((5,7), dtype = int)
    a[zeile,spalte] = 1
    a = bz(a)
    tmp = set()

    if id == 0: nbl = [a << 8, a >> 1, a >> 6]
    elif id == 1: nbl = [a << 7, a >> 6, a >> 8]
    elif id == 2: nbl = [a << 8, a << 2, a >> 8]
    elif id == 3: nbl = [a << 7, a << 1, a >> 7]
    elif id == 4: nbl = [a << 7, a << 1, a >> 1]
    elif id == 5: nbl = [a << 6, a << 1, a >> 1, a >> 6]
    elif id == 6: nbl = [a << 7, a << 2, a >> 2]
    elif id == 7: nbl = [a << 7, a >> 1, a >> 7]
    elif id == 8: nbl = [a << 6, a << 1, a >> 8]  
    elif id == 9: nbl = [a << 6, a >> 2, a >> 6]
    elif id == 10: nbl = [a << 9, a << 5, a >> 6, a >> 8]
    elif id == 11: nbl = [a << 8, a << 6, a >> 6, a >> 8]
    elif id == 12: nbl = [a << 8, a << 1, a >> 1, a >> 8]
    elif id == 13: nbl = [a << 8, a << 6, a << 1, a >> 1]
    elif id == 14: nbl = [a << 8, a << 6, a >> 7]
    elif id == 15: nbl = [a << 14, a >> 7]
    for x in nbl:
        x1b = board7(x)[:,:5]
        if bz(x1b) != 0:
            tmp.add(bz(x1b))
    return tmp

def test_nw():
    for x in nw(16,13): 
        print(board(x))
        print()

test_nw()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]]



In [7]:
def nb(k,id):
    '''
    k: int, 0 - 24, PositionsIndex
    id: int, 0 -15,  Kartenid
    returns: Liste mit den Nachfolge-bitboards bei Spielen der Karte id an Position k für Spieler weiß
    '''
    zeile = k // 5
    spalte = k % 5
    a = np.zeros((5,7), dtype = int)
    a[zeile,spalte] = 1
    a = bz(a)
    tmp = set()

    if id == 0: nbl = [a >> 8, a << 1, a << 6]
    elif id == 1: nbl = [a >> 7, a << 6, a << 8]
    elif id == 2: nbl = [a >> 8, a >> 2, a << 8]
    elif id == 3: nbl = [a >> 7, a >> 1, a << 7]
    elif id == 4: nbl = [a >> 7, a >> 1, a << 1]
    elif id == 5: nbl = [a >> 6, a >> 1, a << 1, a << 6]
    elif id == 6: nbl = [a >> 7, a >> 2, a << 2]
    elif id == 7: nbl = [a >> 7, a << 1, a << 7]
    elif id == 8: nbl = [a >> 6, a >> 1, a << 8]  
    elif id == 9: nbl = [a >> 6, a << 2, a << 6]
    elif id == 10: nbl = [a >> 9, a >> 5, a << 6, a << 8]
    elif id == 11: nbl = [a >> 8, a >> 6, a << 6, a << 8]
    elif id == 12: nbl = [a >> 8, a >> 1, a << 1, a << 8]
    elif id == 13: nbl = [a >> 8, a >> 6, a >> 1, a << 1]
    elif id == 14: nbl = [a >> 8, a >> 6, a << 7]
    elif id == 15: nbl = [a >> 14, a << 7]
    for x in nbl:
        x1b = board7(x)[:,:5]
        if bz(x1b) != 0:
            tmp.add(bz(x1b))
    return tmp

def test_nb():
    for x in nb(8,13): 
        print(board(x))
        print()

test_nb()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



In [8]:
def bb2pos(e):
    ''' e: int, Einzelpos-Bitbaord
    returns: int, Index k der Position
    '''
    return 24 - int(np.log2(e))

def test_bb2pos():
    e = 8
    print(bb2pos(e))

test_bb2pos()

21


In [9]:
# precalculated dictionary pos2bb 
pos2bb = {}
for k in range(25):
    pos2bb[k] = 2 ** (24 - k)
    
def test_pos2bb():
    print(board(pos2bb[13]))

test_pos2bb()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
# precalculated dictionaries (k,id) -> a
nmw = {}    # next map/move white
nmb = {}    # next map/move black
for k in range(25):
    for id in range(16):
        nmw[(pos2bb[k],id)] = nw(k,id)
        nmb[(pos2bb[k],id)] = nb(k,id)
        
def test_nmw():
    for x in nmw[(128,6)]:
        print(board(x))
        print()

test_nmw()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]



In [11]:
def bb(klist):
    '''
    klist: Liste mit Index-Positionen k
    returns: 5x5 Bitboard x mit diesen Positionen
    '''
    tmp = np.zeros((5, 5), dtype = int)
    for k in klist:
        x, y = k // 5, k % 5
        tmp[x,y] = 1
    return bz(tmp)

def bb_test():
    x = bb([21,17,18])
    print(board(x))
    
bb_test()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [0 1 0 0 0]]


In [12]:
def eList(x):
    '''x : int, bitboard  
    returns: Liste mit den Einzelbitboards e von x '''
    return [pos2bb[k] for k in range(25) if (pos2bb[k] & x)]

def eList_test():
    x = bb([21,17,18])
    for e in eList(x):
        print(board(e))
        print()
        
eList_test()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]]



In [13]:
def nextw(x,y,id):
    '''
    x, y: int, bitboard Stellungen
    id: int, Karten id 0-15
    returns: List a of ints, Folgestellungen für weiss mit Karte id für die Positionen aus x, wobei 
             Zielpositionen aus y ausgeschlossen sind
    '''
    tmp = []
    for e in eList(x):
        t = x & ~e
        for z in nmw[(e,id)]:
            if not (z & (x | y)):
                tmp.append(t | z)
    return tmp

def nextb(x,y,id):
    '''
    x, y: int, bitboard Stellung
    id: int, Karten id 0-15
    returns: List a of ints, Folgestellungen für schwarz mit Karte id für die Positionen aus x, wobei 
             Zielpositionen aus y ausgeschlossen sind
    '''
    tmp = []
    for e in eList(x):
        t = x & ~e
        for z in nmb[(e,id)]:
            if not (z & (x | y)):
                tmp.append(t | z)
    return tmp  


def test_nextw():
    x = bb([21,22])
    y = bb([23])
    for z in nextw(x,y,5):
        print(board(z))
        print()
        
def test_nextb():
    x = bb([7])
    y = bb([8])
    for z in nextb(x,y,3):
        print(board(z))
        print()
        
test_nextb()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]



In [14]:
def minus(x,y):
    ''' x, y bitboard
    returns bitboard x minus Positions in bitboard y '''
    return x & ~y

def test_minus():
    x = bb([20,21,22])
    y = bb([22,23])
    print(board(minus(x,y)))
    
test_minus()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 0 0 0]]


In [15]:
'''
beim dem Ausdruck von show bedeutet
player: 0 = als nächstes ist weiß dran
turn: 0 = bis jetzt wurden 0 Züge gemacht

'''

def show(state):
    sw, sb, mw, mb, ids, player, turn = state
    a = np.zeros((5,5), dtype = int)
    for x in range(5):
        for y in range(5):
            if board(sw)[x,y] == 1:
                a[x,y] = 1
            if board(sb)[x,y] == 1:
                a[x,y] = 3
            if board(mw)[x,y] == 1:
                a[x,y] = 2
            if board(mb)[x,y] == 1:
                a[x,y] = 4

    print(a)
    print('ids:',ids, 'player:',player, 'turn:',turn)
    
def startstate():
    sw = bb([20,21,23,24])
    sb = bb([0,1,3,4])
    mw = bb([22])
    mb = bb([2])
    ids = (2,3,8,14,10)
    player = 0
    turn = 0
    return sw, sb, mw, mb, ids, player, turn

def teststate():
    sw = bb([22])
    mw = bb([])
    sb = bb([21])
    mb = bb([23])
    ids = (2,3,8,14,10)
    player = 0
    turn = 0
    return sw, sb, mw, mb, ids, player, turn

def test_show():
    print(teststate())
    show(teststate())
    
test_show()

(4, 8, 0, 2, (2, 3, 8, 14, 10), 0, 0)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 3 1 4 0]]
ids: (2, 3, 8, 14, 10) player: 0 turn: 0


In [16]:
def swap(tup,i,j):
    ''' vertauscht im tuple tup die indizes i und j'''
    tmp = list(tup)
    tmp[i],tmp[j] = tmp[j],tmp[i]
    return tuple(tmp)

def test_swap():
    ids = (2,3,8,14,10)
    print(swap(ids,1,4))
    
test_swap()


(2, 10, 8, 14, 3)


In [17]:
'''
wenn es keinen gültigen Zug gibt, kann man PASS sagen und eine Karte tauschen

'''

def nextstates(state):
    sw, sb, mw, mb, ids, player, turn = state
    tmp = []    
    if player == 0:
        player = 1
        turn += 1
        for i in range(0,2):
            id = ids[i]
            ids_neu = swap(ids,i,4)
            for x in nextw(sw,mw,id):
                sb_neu = minus(sb,x)
                mb_neu = minus(mb,x)
                tmp.append((x,sb_neu,mw,mb_neu,ids_neu,player,turn))
            for x in nextw(mw,sw,id):
                sb_neu = minus(sb,x)
                mb_neu = minus(mb,x)
                tmp.append((sw,sb_neu,x,mb_neu,ids_neu,player,turn))
        if len(tmp) == 0:   # kein gültiger Zug gefunden
            tmp.append((sw,sb,mw,mb,swap(ids,0,4),player,turn))
            tmp.append((sw,sb,mw,mb,swap(ids,1,4),player,turn))
                
                
    elif player == 1:
        player = 0
        turn += 1
        
        for i in range(2,4):
            id = ids[i]
            ids_neu = swap(ids,i,4)
            for x in nextb(sb,mb,id):
                sw_neu = minus(sw,x)
                mw_neu = minus(mw,x)
                tmp.append((sw_neu,x,mw_neu,mb,ids_neu,player,turn))
            for x in nextb(mb,sb,id):
                sw_neu = minus(sw,x)
                mw_neu = minus(mw,x)
                tmp.append((sw_neu,sb,mw_neu,x,ids_neu,player,turn))
        if len(tmp) == 0:   # kein gültiger Zug gefunden
            tmp.append((sw,sb,mw,mb,swap(ids,2,4),player,turn))
            tmp.append((sw,sb,mw,mb,swap(ids,3,4),player,turn))
    return tmp 

def test_nextstates():
    sw = bb([22])
    mw = bb([])
    sb = bb([21])
    mb = bb([23])
    ids = (3,5,4,4,0)
    player = 0
    turn = 0
    state = (sw,sb,mw,mb,ids,player,turn)
    show(state)
    print('====')
    for st in nextstates(state):
        show(st)
        print('----')

def test_nextstates1():
    sw = bb([4,9,14,24])
    mw = bb([19])
    sb = bb([21])
    mb = bb([23])
    ids = (15,7,4,5,0)
    player = 0
    turn = 0
    state = (sw,sb,mw,mb,ids,player,turn)
    show(state)
    print('====')
    for st in nextstates(state):
        show(st)
        print('----')
        
test_nextstates1()
 
 

[[0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 2]
 [0 3 0 4 1]]
ids: (15, 7, 4, 5, 0) player: 0 turn: 0
====
[[0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 2]
 [0 3 0 4 1]]
ids: (0, 7, 4, 5, 15) player: 1 turn: 1
----
[[0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 2]
 [0 3 0 4 1]]
ids: (15, 0, 4, 5, 7) player: 1 turn: 1
----


In [18]:
def getPosNamen():
    '''e bitboard einer Einzelposition
    returns: Positionsname wie in Codingame: A1 für Index 20'''
    tmp = {}
    tmp1 = []
    for i in range(5,-1,-1):
        for c in 'ABCDE':
            tmp1.append(c+str(i))
    tmp2 = [pos2bb[k] for k in range(25)]
    for x,name in zip(tmp2,tmp1):
        tmp[x]=name
    return tmp
    
posNamen = getPosNamen()
print(posNamen[bb([8])])

D4


In [19]:
def zug(b1, b2):
    ''' zwei bitboards b2 entsteht aus b1, indem ein bit aus b1 an eine andere stelle gewandert ist'''
    ''' returns 2 bitboards: die von-Position des gewanderten bits und die zu-Position'''
    return posNamen[b1 & ~b2]+posNamen[b2 & ~b1]

def test_zug():
    b1 = bb([21,22])
    b2 = bb([22,23])
    print(zug(b1,b2))
    
test_zug()

B1D1


In [20]:
def getMsg(state1, state2):
    sw1, sb1, mw1, mb1, ids1, player1, turn1 = state1
    sw2, sb2, mw2, mb2, ids2, player2, turn2 = state2
    cardid = ids2[-1]
    if player1 == 0:  # es war ein Zug von weiss
        allw1 = sw1 | mw1
        allw2 = sw2 | mw2
        if allw1 == allw2: return "PASS"
        return str(cardid) + " " + zug(allw1, allw2)
    if player1 == 1:
        allb1 = sb1 | mb1
        allb2 = sb2 | mb2
        if allb1 == allb2: return "PASS"
        return str(cardid) + " " + zug(allb1, allb2)
    
def test_getMsg():
    sw = bb([22])
    mw = bb([])
    sb = bb([21])
    mb = bb([23])
    ids = (3,5,4,4,0)
    player = 0
    turn = 0
    state = (sw,sb,mw,mb,ids,player,turn)
    for st in nextstates(state):
        show(st)
        print(getMsg(state,st))
        print("----")
        
test_getMsg()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 3 0 4 0]]
ids: (0, 5, 4, 4, 3) player: 1 turn: 1
3 C1C2
----
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 4 0]]
ids: (0, 5, 4, 4, 3) player: 1 turn: 1
3 C1B1
----
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 3 0 4 0]]
ids: (3, 0, 4, 4, 5) player: 1 turn: 1
5 C1D2
----
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 4 0]]
ids: (3, 0, 4, 4, 5) player: 1 turn: 1
5 C1B1
----
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 3 0 1 0]]
ids: (3, 0, 4, 4, 5) player: 1 turn: 1
5 C1D1
----


In [21]:
mfb = bb([2])  # meister feld black
mfw = bb([22]) # meister feld white
def goaltest(state):
    sw, sb, mw, mb, ids, player, turn = state
    return mw == mfb or mb == mfw or mw == 0 or mb == 0 or turn > 200


def test_goaltest():
    sw = bb([22])
    mw = bb([3])
    sb = bb([21])
    mb = bb([])
    ids = (3,5,4,7,0)
    player = 0
    turn = 0
    state = (sw,sb,mw,mb,ids,player,turn)
    show(state)
    print(goaltest(state))
    
    
test_goaltest()   

[[0 0 0 2 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 3 1 0 0]]
ids: (3, 5, 4, 7, 0) player: 0 turn: 0
True


In [22]:
def countBits(x):
    ''' nicht effizient '''
    return bin(x).count('1')

def test_countBits():
    x = 12
    print(countBits(x))
    
test_countBits()

2


In [23]:
def evaluation(state):
    sw, sb, mw, mb, ids, player, turn = state
    if mw == mfb or mb == 0: return 10000
    if mb == mfw or mw == 0: return -10000
    pw = countBits(sw)*40
    pb = countBits(sb)*40
    return pw - pb

def test_evaluation():
    sw = bb([22,23])
    mw = bb([1])
    sb = bb([21,17,18])
    mb = bb([20])
    ids = (3,5,4,7,0)
    player = 0
    turn = 0
    state = (sw,sb,mw,mb,ids,player,turn)
    print(evaluation(state))
    
test_evaluation()
    
    
    

-40


In [26]:
def boardlist2bbs(bl):
    ''' einer boardlist die bitboards für ein state'''
    swl, sbl, mwl, mbl = [], [], [], []
    for k in range(25):
        if bl[k] == 'b': sbl.append(k)
        elif bl[k] == 'B': mbl.append(k)
        elif bl[k] == 'w': swl.append(k)
        elif bl[k] == 'W': mwl.append(k)
            
    return bb(swl),bb(sbl),bb(mwl),bb(mbl)
            

def boardlist2bbs_test():
    bl =  ['b', 'b', 'B', 'b', 'b', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', 'w', 'w', 'W', 'w', 'w']
    sw, sb, mw, mb = boardlist2bbs(bl)
    print(board(sw))
    print(board(mw))
    print(board(sb))
    print(board(mb))
    
boardlist2bbs_test()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 0 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]
[[1 1 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### Die Indexpositionen des 5x5 Bitboards

In [12]:
a = np.arange(25)
a = a.reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Modellierung des Spielstatus

Eine Spielstellung ist vollständig beschrieben durch 
- die Lage auf dem Brett (die 4 Bitboards: sw, sb, mw, mb )
Stellung der weißen, Stellung der schwarzen, Stellung der Meister
- die Verteilung der Karten (id0 .. id4 in einer Liste)
- wer dran ist (der untere (weisse) Spieler 0 oder der obere (schwarze) Spieler ist 1)
-  der wievielte Zug es ist. Bei 200 endet das Spiel.


```
status = [sw, sb, mw, mb, ids, player(0/1), turn(0-200)]  
```

<img src = './img/onitama01.png' width = 500>





 

Die Funktion show zeigt das Brett mit:
```
0 - frei
1 - Schüler Spieler 1
2 - Meister Spieler 1
3 - Schüler Spieler 2
4 - Meister Spieler2

```

#### Eine Abfolge von 10 zufälligen Zügen zum Test

In [73]:
import random
state = startstate()
show(state)
print('=====')
for i in range(10):
    ns = nextstates(state)
    i = random.randint(0,len(ns)-1)
    print(getMsg(state,ns[i]))
    state = ns[i]
    show(state)
    print('-----')

[[3 3 4 3 3]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 2 1 1]]
ids: (2, 3, 8, 14, 10) player: 0 turn: 0
=====
2 D1C2
[[3 3 4 3 3]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [1 1 2 0 1]]
ids: (10, 3, 8, 14, 2) player: 1 turn: 1
-----
8 C5B4
[[3 3 0 3 3]
 [0 4 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [1 1 2 0 1]]
ids: (10, 3, 2, 14, 8) player: 0 turn: 2
-----
10 C2A3
[[3 3 0 3 3]
 [0 4 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 2 0 1]]
ids: (8, 3, 2, 14, 10) player: 1 turn: 3
-----
14 E5D4
[[3 3 0 3 0]
 [0 4 0 3 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 2 0 1]]
ids: (8, 3, 2, 10, 14) player: 0 turn: 4
-----
8 C1D2
[[3 3 0 3 0]
 [0 4 0 3 0]
 [1 0 0 0 0]
 [0 0 0 2 0]
 [1 1 0 0 1]]
ids: (14, 3, 2, 10, 8) player: 1 turn: 5
-----
10 D4C5
[[3 3 3 3 0]
 [0 4 0 0 0]
 [1 0 0 0 0]
 [0 0 0 2 0]
 [1 1 0 0 1]]
ids: (14, 3, 2, 8, 10) player: 0 turn: 6
-----
3 B1B2
[[3 3 3 3 0]
 [0 4 0 0 0]
 [1 0 0 0 0]
 [0 1 0 2 0]
 [1 0 0 0 1]]
ids: (14, 10, 2, 8, 3) player: 1 turn: 7
-----
8 B4A3
[[3 3 3 3 0]
 [0 0 0 0 0]
 [4 0 0 0 0

-----