## Bitboards

Literatur: [Bitboard Methods for Games](./data/bitboard_methods_for_games.pdf)


#### Beispiel 1:
Ein 5x5 quadratisches Bitboard mit Trennspalte an der rechten Seite

In [2]:
import numpy as np
 
bb = np.ones((5, 6), dtype = int)
bb[:,5] = 0
bb

array([[1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0]])

In [3]:
def bz(a):
    return int(''.join([str(x) for x in a.flatten()]),2)

def board(k):
    bs = bin(k)[2:]
    bs = bs.rjust(30,'0')
    bs = bs[len(bs)-30:]
    i, j = 0, 0
    tmp = np.zeros((5, 6), dtype = int)
    for c in bs:
        tmp[i,j] = int(c)
        j = j+1
        if j > 5:
            j = 0
            i = i+1
    return tmp

In [4]:
k = bz(bb)
board(k)

array([[1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0]])

#### Namenskonventionen

```
bitsw = weiße Figuren
bitsb = schwarze Figuren
bitsp = Figuren des aktuellen Spielers
bitso = Figuren des aktuell oppositionellen Spielers
bitsm = die Zelle, die Ausgangspunkt des letzten Zugs war
mask =  alle Zellen, die auf dem zum Spielbrett gehören (also alle außer der Trennspalte)
maskw = alle weißen Zellen eines dameartigen Bretts
maskb = alle schwarzen Zellen eines dameartigen Bretts
|bits| = Anzahl 1er in bits
full = bitsw | bitsb = alle Figuren
empty = !full & mask = alle unbesetzten Zellen
emptyp = alle vom aktuellen Spieler nicht besetzten Zellen
emptyo = all vom aktuell oppositionellen Spieler nicht besetzten Zellen
```



#### Beispiel Onitama:

In [5]:
# Alle Felder des Bretts
mask = np.ones((5, 6), dtype = int)
mask[:,5] = 0
mask = bz(mask)
mask

1056698302

In [6]:
# Ausgangsposition für weiß 
bitsw = np.zeros((5,6), dtype = int)
bitsw[4,0:5] = 1
bitsw = bz(bitsw)
print(bitsw)
print(board(bitsw))
 

62
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 1 1 0]]


In [7]:
# Ausgangsposition für schwarz 
bitsb = np.zeros((5,6), dtype = int)
bitsb[0,0:5] = 1
bitsb = bz(bitsb)
print(bitsb)
print(board(bitsb))

1040187392
[[1 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [8]:
# alle Figuren
full = bitsw | bitsb
print(full)
print(board(full))
 

1040187454
[[1 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 1 1 0]]


In [9]:
# alle leeren Felder
empty = ~full & mask
print(empty)
board(empty)


16510848


array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

#### Logische Operationen

In [10]:
# union |
a = np.zeros((5,6), dtype = int)
a[1,0] = 1
a = bz(a)
b = np.zeros((5,6), dtype = int)
b[1,3] = 1
b = bz(b)
board(a | b)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [11]:
# Komplement
board(~a & mask)

array([[1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0]])

In [12]:
# exclusive or
a = np.zeros((5,6), dtype = int)
b = np.zeros((5,6), dtype = int)
a[2,:] = 1
b[:,2] = 1
a, b = bz(a), bz(b)
board(a ^ b)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [13]:
# intersection
board(a & b)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

#### Morphologische Operationen

#### Dilation

In [14]:
a = np.zeros((5,6), dtype = int)
a[2,2] = 1
a = bz(a)
board(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [15]:
board(a | a >> 1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
# die vier richtungen von der mitte aus
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
# die vier richtungen von der linken Seite aus
a = np.zeros((5,6), dtype = int)
a[2,0] = 1
a = bz(a)
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [22]:
# die vier richtungen von der rechten Seite aus
a = np.zeros((5,6), dtype = int)
a[2,4] = 1
a = bz(a)
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [23]:
# die vier richtungen von der ersten Zeile aus
a = np.zeros((5,6), dtype = int)
a[0,2] = 1
a = bz(a)
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[0, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [24]:
# die vier richtungen von der letzten Zeile aus
a = np.zeros((5,6), dtype = int)
a[4,2] = 1
a = bz(a)
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0]])

In [25]:
# die vier richtungen von oben links aus
a = np.zeros((5,6), dtype = int)
a[0,0] = 1
a = bz(a)
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [26]:
# die vier richtungen von unten rechts aus
a = np.zeros((5,6), dtype = int)
a[4,4] = 1
a = bz(a)
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 1]])

In [27]:
# dilation mit mehreren Zellen
a = np.zeros((5,6), dtype = int)
a[2,1] = 1
a[2,3] = 1
a = bz(a)
board(a | a << 1 | a >> 1 | a >> 6 | a << 6)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [62]:
def dilation(a):
    return a | a << 1 | a >> 1 | a >> 6 | a << 6

#### Erosion

Die Null dehnt sich nach rechts aus. Aber hier müsste wohl die obere Zeile auch eine Begrenzung sein. Etwas unklar

In [61]:
a = np.ones((5,6), dtype = int)

a[2,1]=0
a = bz(a)
print(board(a))
print()
b = a & a >> 1
print(board(b))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 0 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[0 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 0 0 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


 ### Algorithmen
 
 Filter, Queries und Updates

In [69]:
def getbz(aList):
    ''' aList = Liste von Koordinaten-Tupels
    returns: bitzahl für das entsprechende board'''
    tmp = np.zeros((5,6), dtype = int)
    for x,y in aList:
        tmp[x,y] = 1
    return bz(tmp)
        
    
    

### Filter

Filter lesen ein Bitboard und erzeugen neue Bitboards, z.B. die gültigen Züge (mein Fall!)

#### Nachbar Filter

In [70]:
# die Nachbarfelder aller Figuren
a = dilation(full) & empty
board(a)

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [91]:
b = [(0,0),(1,1),(1,2)]
w = [(3,0),(4,1),(3,4)]
bitsw = getbz(w)
bitsb= getbz(b)
full = bitsw | bitsb
print(board(full))
print()
empty = ~full & mask
a = dilation(full) & empty  # alle leeren Nachbarfelder
print(board(a))


[[1 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 1 0]
 [0 1 0 0 0 0]]

[[0 1 1 0 0 0]
 [1 0 0 1 0 0]
 [1 1 1 0 1 0]
 [0 1 0 1 0 0]
 [1 0 1 0 1 0]]


In [107]:
def dirs(a):
    '''N, E, S, W'''
    tmp = [a << 6, a >> 1, a >> 6, a << 1]
    return tmp

# die Nachbarfelder des weißen Spielers in nördlicher Richtung:
print(board(bitsw))
print()

for d in dirs(bitsw):
    print(board(d & empty))
    print()
    

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 1 0]
 [0 1 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 1 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 0]]



## Onitama
Aufgabe 1: Gegeben die weißen Figuren in Grundstellung. Generiere alle Nachfolgestellungen für weiß bei Karte 9:

```
. . x
x o .
. . x

```


In [109]:
dirs = {}

def ns(e, id):
    ''' e bitboard einer Position'''
    if id == 9:
        return [e << 1, e << 6, e >> 8]
        

a = np.zeros((5,6), dtype = int)
a[4,0] = 1
a = bz(a)
for x in ns(a,9):
    print(board(x))
    print()

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

