In [2]:
import numpy as np

#### Zeilensummen, Spaltensummen und Prozente

In [10]:
A = np.array([[5,3,8],[8,6,9],[6,4,2]])
A

array([[5, 3, 8],
       [8, 6, 9],
       [6, 4, 2]])

In [11]:
b = A.sum(axis = 0)   # addiert die Spalten auf
c = A.sum(axis = 1)   # addiert die Zeilen auf
b, c

(array([19, 13, 19]), array([16, 23, 12]))

In [14]:
b.reshape(1,3)    # aus dem Array wird eine 1x3 Matrix

array([[19, 13, 19]])

In [15]:
A*100

array([[500, 300, 800],
       [800, 600, 900],
       [600, 400, 200]])

In [16]:
A*100/b.reshape(1,3)      # die Prozentzahlen bezogen auf die Spaltensumme

array([[26.31578947, 23.07692308, 42.10526316],
       [42.10526316, 46.15384615, 47.36842105],
       [31.57894737, 30.76923077, 10.52631579]])

In [81]:
A = np.array([(5,3,8),(8,6,9),(6,4,2)])      # zun Erzeugen kann man auch Tuples nehmen, liest sich besser
A , A.shape

(array([[5, 3, 8],
        [8, 6, 9],
        [6, 4, 2]]), (3, 3))

#### Broadcasting

In [19]:
v = np.array([2,4,5,8])
v + 100

array([102, 104, 105, 108])

In [26]:
m = np.array([[1,2,3],[4,5,6]])
v = np.array([100,200,300])       # Der (1,3)-Zeilenvektor wird zu einer (2,3) Matrix erweitert
m + v

array([[101, 202, 303],
       [104, 205, 306]])

In [30]:
m = np.array([[1,2,3],[4,5,6]])
v = np.array([[100],[200]])       # Der (2,1) Spaltenvektor wird zu einer (2,3) Matrix erweitert
m + v

array([[101, 102, 103],
       [204, 205, 206]])

In [34]:
r = np.array([[1,2,3]])
c = np.array([[4],[5],[6]])
r + c                             # auch das ergibt eine Matrix!

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [35]:
r * c

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

#### Vektoren erzeugen

In [61]:
# rankn: Werte der Standardnormalverteilung
a = np.random.randn(5)           # rank 1 array
b = np.random.randn(2,3)         # Matrix
a, b

(array([ 0.49430258,  0.63845859, -1.45623899,  0.27008142,  0.37284234]),
 array([[-0.02976122,  0.60406546, -1.44540895],
        [-3.24332451,  0.49359782, -1.70283741]]))

In [58]:
a.shape, b.shape                    

((5,), (2, 2))

**TIP**: Keine Strukturen benutzen, die Shape (5,) haben (**rank 1 array**). Das ist Da kann es bei Operationen unintuitive Effekte geben. Das ist weder ein Zeilenvektor noch ein Spaltenvektor. Stattdessen:

In [71]:
a = np.random.randn(5,1)      # Spaltenvektor
assert(a.shape == (5,1))      # Kontrolle
a

array([[ 1.5118283 ],
       [-0.23732718],
       [ 0.00585478],
       [ 0.8553403 ],
       [-1.66665642]])

In [72]:
b = np.random.randn(1,5)      # Zeilenvektor
assert(b.shape == (1,5))      # Kontrolle
b


array([[-0.84245147, -0.58503289,  2.00281063,  0.6436177 ,  0.25453595]])

Wenn man doch einmal ein rank 1 array hat, kann man es reshapen

In [75]:
a = np.random.randn(5)
a.reshape(1,5)

array([[0.96463289, 0.36190416, 1.56050768, 1.05729856, 0.60781053]])

#### Numpy vs Math

Die Funktionen in math können meist nicht auf Vektoren angewendet werden.

In [7]:
import math
a = np.array([(1,2,3)])
#  math.exp(a)      # wirft fehler
np.exp(a)

array([[ 2.71828183,  7.3890561 , 20.08553692]])

#### Arange

In [31]:
a = np.arange(0,30,1)
a = a.reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
b = a.reshape(2,3,5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [35]:
len(b)

2

In [33]:
b.T

array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])

In [ ]:
b = a.reshape(5,2,2)

#### Reshape  

In [8]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [9]:
image.shape

(3, 3, 2)

In [10]:
image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

In [19]:
a = np.random.randint(5,size=(4,2,3,2))
print(a)
a_flatten = a.reshape(4, -1).T
#a_flatten = a.reshape(a.shape[0], -1).T      # X.T is the transpose of X
a_flatten

[[[[4 1]
   [3 4]
   [3 3]]

  [[3 1]
   [1 0]
   [0 1]]]


 [[[0 3]
   [4 0]
   [1 3]]

  [[2 3]
   [0 2]
   [2 2]]]


 [[[3 0]
   [2 4]
   [3 1]]

  [[4 3]
   [2 4]
   [3 3]]]


 [[[0 1]
   [1 2]
   [4 0]]

  [[1 2]
   [4 3]
   [0 2]]]]


array([[4, 0, 3, 0],
       [1, 3, 0, 1],
       [3, 4, 2, 1],
       [4, 0, 4, 2],
       [3, 1, 3, 4],
       [3, 3, 1, 0],
       [3, 2, 4, 1],
       [1, 3, 3, 2],
       [1, 0, 2, 4],
       [0, 2, 4, 3],
       [0, 2, 3, 0],
       [1, 2, 3, 2]])

#### Normalisieren

In [13]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [14]:
c.shape


(12288, 45)

In [15]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [16]:
c

array([[ 0.64855211,  0.05280275, -0.56621383],
       [-0.3828648 ,  1.22545928, -0.2365205 ],
       [-0.74080594,  0.22464472,  0.01670728]])

#### Slicing

#### Squeeze

In [20]:
b = np.random.randn(3, 1)
b

array([[-0.16653093],
       [ 0.56030136],
       [-1.01970398]])

In [22]:
c = np.squeeze(b)
print(c.)

array([-0.16653093,  0.56030136, -1.01970398])

#### Zeros

In [38]:
a = np.zeros((1,9))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])