#### Shapes of numpy Arrays

In [1]:
import numpy as np

In [4]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
b = a.reshape(2,3,5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [16]:
len(b), len(b[0]), len(b[0,0]), b.shape

(2, 3, 5, (2, 3, 5))

In [20]:
bt = b.T
bt

array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])

In [21]:
bt.shape

(5, 3, 2)

In [37]:
b.reshape(3,-1)
 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
c = a.reshape(2,5,3)

In [23]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [26]:
ct = c.T
print(ct.shape)
ct

(3, 5, 2)


array([[[ 0, 15],
        [ 3, 18],
        [ 6, 21],
        [ 9, 24],
        [12, 27]],

       [[ 1, 16],
        [ 4, 19],
        [ 7, 22],
        [10, 25],
        [13, 28]],

       [[ 2, 17],
        [ 5, 20],
        [ 8, 23],
        [11, 26],
        [14, 29]]])

In [28]:
d = a.reshape(3,5,2)
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

RGB-Daten für ein Bild 5x5 Pixel Bild werden in einer 5x5x3 Matrix geliefert.


In [59]:
np.random.seed(42)
a = np.random.randint(0,256,size=(25*3))
print(a)
a.reshape(5,5,3)

[102 179  92  14 106  71 188  20 102 121 210 214  74 202  87 116  99 103
 151 130 149  52   1  87 235 157  37 129 191 187  20 160 203  57  21 252
 235  88  48 218  58 254 169 255 219 187 207  14 189 189 174 189  50 107
  54 243  63 248 130 228  50 134  20  72 166  17 131  88  59  13 241 249
   8  89  52]


array([[[102, 179,  92],
        [ 14, 106,  71],
        [188,  20, 102],
        [121, 210, 214],
        [ 74, 202,  87]],

       [[116,  99, 103],
        [151, 130, 149],
        [ 52,   1,  87],
        [235, 157,  37],
        [129, 191, 187]],

       [[ 20, 160, 203],
        [ 57,  21, 252],
        [235,  88,  48],
        [218,  58, 254],
        [169, 255, 219]],

       [[187, 207,  14],
        [189, 189, 174],
        [189,  50, 107],
        [ 54, 243,  63],
        [248, 130, 228]],

       [[ 50, 134,  20],
        [ 72, 166,  17],
        [131,  88,  59],
        [ 13, 241, 249],
        [  8,  89,  52]]])

In [60]:
print(a.shape)
a[::3] = 0
a

(75,)


array([  0, 179,  92,   0, 106,  71,   0,  20, 102,   0, 210, 214,   0,
       202,  87,   0,  99, 103,   0, 130, 149,   0,   1,  87,   0, 157,
        37,   0, 191, 187,   0, 160, 203,   0,  21, 252,   0,  88,  48,
         0,  58, 254,   0, 255, 219,   0, 207,  14,   0, 189, 174,   0,
        50, 107,   0, 243,  63,   0, 130, 228,   0, 134,  20,   0, 166,
        17,   0,  88,  59,   0, 241, 249,   0,  89,  52])

In [53]:
a

array([  0, 179,  92,  14, 106,  71, 188,  20,   0, 121,   0, 214,  74,
       202,   0, 116,   0, 103, 151, 130, 149,  52,   1,   0, 235, 157,
        37,   0, 191, 187,  20, 160, 203,   0,   0,   0, 235,  88,   0,
       218,  58, 254, 169,   0,   0, 187,   0,  14,   0,   0,   0,   0,
        50, 107,   0,   0,   0, 248, 130,   0,  50, 134,  20,   0, 166,
        17, 131,  88,  59,  13, 241,   0,   8,  89,  52])