## Pytorch

### Tensoren

Tensoren sind eine Verallgemeinerung von Vektoren und Matrizen in höhere Dimensionen

Auf die Daten eines Tensors mit Dimension 1 (oder Rang) können wir mit einem Index zugreifen. Wir stellen uns den
Tensor als Vektor vor. 

#### Dimension 1

In [20]:
import torch
a = [1,2,3]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1].item())

tensor([1, 2, 3])
shape: torch.Size([3])
dim: 1
Zugriff auf ein Element: 2


#### Dimension 2

Auf die Daten eines Tensors mit Dimension 2 können wir mit 2 Indizes zugreifen. Wir stellen uns den Tensor als Matrix vor.

In [21]:
import torch
a = [[1,2,3],[4,5,6]]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1][2].item())

tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])
dim: 2
Zugriff auf ein Element: 6


#### Dimension 3

Auf die Daten eines Tensors mit Dimension 3 können wir mit 3 Indizes zugreifen. Wir stellen uns den Tensor als Quader (hintereinander gestapelte Matrizen) vor.

In [22]:
a = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1][1][1].item())

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
shape: torch.Size([2, 2, 3])
dim: 3
Zugriff auf ein Element: 11


#### Dimension 4

Auf die Daten eines Tensors mit Dimension 4 können wir mit 4 Indizes zugreifen. Wir stellen uns den Tensor als eine Vektor von Quadern vor.  


In [23]:
a = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1][1][1][1].item())

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]]])
shape: torch.Size([2, 2, 2, 3])
dim: 4
Zugriff auf ein Element: 23


<img src="./img/nn-tensoren.png" width="600"/>    

#### Reshape

Mit Reshape können wir die Gestalt des Tensors verändern. 

In [24]:
a = list(range(2*3*4*5))
t = torch.tensor(a)    # ein Vektor mit 120 Elementen
t 

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119])

In [25]:
t.reshape(2,60)   # Matrix mit 2 Zeilen, 60 Spalten  

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
          88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
         102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
         116, 117, 118, 119]])

In [ ]:
t.reshape(60,2)   # Matrix mit 60 Zeilen, 2 Spalten

In [26]:
t.reshape(2,3,20) # 2 Matrizen mit je 3 Zeilen und 20 Spalten hintereinander gestapelt

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
           14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
           34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
           54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
           74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
           94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
          114, 115, 116, 117, 118, 119]]])

In [27]:
t.reshape(2,3,20)[1][2][17]

tensor(117)

In [28]:
t.reshape(2,3,4,5)[1][1][2][3]  # 2 Quader, bestehend aus 3 hintereinandergestapelten 4x5 Matrizen  

tensor(93)

In [29]:
t.reshape(2,4,3,5)[1][1][2][3] # 2 Quader, bestehend aus 4 hintereinandergestapelten 3x5 Matrizen   

tensor(88)

<img src="./img/nn-reshape.png" width="800"/>    



### Ein Netz für die OR-Funktion

In [30]:
import torch
import torch.optim as optim
import torch.nn.functional as F
import torch.nn as nn
import numpy as np

In [31]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,1)
 
    def forward(self, t):
        t = self.fc1(t)
        t = torch.sigmoid(t)
        return t

In [32]:
X = torch.Tensor([[0,0],[0,1],[1,0],[1,1]]).reshape(4,1,2)
Y = torch.Tensor([0,1,1,1]).reshape(4,1,1)

net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.1)
loss_fn = torch.nn.MSELoss(reduction='mean')

for epoch in range(5000):
    Y_hat = net(X)
    loss = loss_fn(Y_hat, Y)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
            
print(net(X))
print(net(X).shape)
print(list(net.parameters()))

tensor([[[0.1207]],

        [[0.9259]],

        [[0.9260]],

        [[0.9991]]], grad_fn=<SigmoidBackward>)
torch.Size([4, 1, 1])
[Parameter containing:
tensor([[4.5133, 4.5117]], requires_grad=True), Parameter containing:
tensor([-1.9862], requires_grad=True)]


<img src="img/nn-netX.png" width="500"> 

### Ein Netz für die XOR-Funktion

Bei zwei Neuronen im hidden-Layer kann man schon mal Pech haben. Aber bei drei klappt es meistens. 

In [33]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,3)
        self.fc2 = nn.Linear(3,1)
 
    def forward(self, t):
        t = self.fc1(t)
        t = torch.relu(t)
        t = self.fc2(t)
        t = torch.sigmoid(t)
        return t

In [34]:
X = torch.Tensor([[0,0],[0,1],[1,0],[1,1]]).reshape(4,1,2)
Y = torch.Tensor([0,1,1,0]).reshape(4,1,1)

net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.1)
loss_fn = torch.nn.MSELoss(reduction='mean')

for epoch in range(6000):
    Y_hat = net(X)
    loss = loss_fn(Y_hat, Y)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
            
print(net(X))

tensor([[[0.0572]],

        [[0.9619]],

        [[0.9636]],

        [[0.0312]]], grad_fn=<SigmoidBackward>)
