#### Die OR und XOR Funktion mit Pytorch

In [2]:
import torch
import torch.optim as optim
import torch.nn.functional as F
import torch.nn as nn
import numpy as np

#### Ein Netz für die OR-Funktion

In [3]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,1)
 
    def forward(self, t):
        t = self.fc1(t)
        t = torch.sigmoid(t)
        return t

In [12]:
X = torch.Tensor([[0,0],[0,1],[1,0],[1,1]]).reshape(4,1,2)
Y = torch.Tensor([0,1,1,1]).reshape(4,1,1)

net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.1)
loss_fn = torch.nn.MSELoss(reduction='mean')

for epoch in range(2000):
    Y_hat = net(X)
    loss = loss_fn(Y_hat, Y)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
            
print(net(X))
print(net(X).shape)
print(list(net.parameters()))

tensor([[[0.2053]],

        [[0.8776]],

        [[0.8777]],

        [[0.9950]]], grad_fn=<SigmoidBackward>)
torch.Size([4, 1, 1])
[Parameter containing:
tensor([[3.3246, 3.3229]], requires_grad=True), Parameter containing:
tensor([-1.3535], requires_grad=True)]


<img src="img/nn-netX.png" width="500"> 




#### Ein Netz für die XOR-Funktion

Bei zwei Neuronen im hidden-Layer kann man schon mal Pech haben. Aber bei drei klappt es meistens. 

In [23]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,3)
        self.fc2 = nn.Linear(3,1)
 
    def forward(self, t):
        t = self.fc1(t)
        t = torch.relu(t)
        t = self.fc2(t)
        t = torch.sigmoid(t)
        return t

In [25]:
X = torch.Tensor([[0,0],[0,1],[1,0],[1,1]]).reshape(4,1,2)
Y = torch.Tensor([0,1,1,0]).reshape(4,1,1)

net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.1)
loss_fn = torch.nn.MSELoss(reduction='mean')

for epoch in range(6000):
    Y_hat = net(X)
    loss = loss_fn(Y_hat, Y)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
            
print(net(x))

tensor([[[0.0257]],

        [[0.9560]],

        [[0.9560]],

        [[0.0257]]], grad_fn=<SigmoidBackward>)
