## Tensoren

Tensoren sind eine Verallgemeinerung von Vektoren und Matrizen in höhere Dimensionen

Auf die Daten dieses Tensors können wir mit einem Index zugreifen. Der Rang (oder Dimension des Tensors ist 1). Wir stellen uns den
Tensor als Vektor vor.

#### Dimension 1

In [1]:
import torch
a = [1,2,3]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1].item())

tensor([1, 2, 3])
shape: torch.Size([3])
dim: 1
Zugriff auf ein Element: 2


#### Dimension 2

Auf die Daten eines Tensors mit Dimension 2 können wir mit 2 Indizes zugreifen. Wir stellen uns den Tensor als Matrix vor.

In [15]:
import torch
a = [[1,2,3],[4,5,6]]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1][1].item())

tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])
dim: 2
Zugriff auf ein Element: 5


#### Dimension 3

Auf die Daten eines Tensors mit Dimension 3 können wir mit 3 Indizes zugreifen. Wir stellen uns den Tensor als Quader (hintereinander gestapelte Matrizen) vor.

In [19]:
a = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1][1][1].item())

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
shape: torch.Size([2, 2, 3])
dim: 3
Zugriff auf ein Element: 11


#### Dimension 4

Auf die Daten eines Tensors mit Dimension 4 können wir mit 4 Indizes zugreifen. Wir stellen uns den Tensor als eine Vektor von Quadern vor.  


In [21]:
a = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]
t = torch.tensor(a)
print(t)
print("shape:", t.shape)
print("dim:", t.dim())
print("Zugriff auf ein Element:", t[1][1][1][1].item())

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]],


        [[[13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24]]]])
shape: torch.Size([2, 2, 2, 3])
dim: 4
Zugriff auf ein Element: 23


<img src="./img/nn-tensoren.png" width="600"/>    

### Reshape

Mit Reshape können wir die Gestalt des Tensors verändern. 

In [47]:
a = list(range(2*3*4*5))
t = torch.tensor(a)    # ein Vektor mit 120 Elementen
t

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119])

In [48]:
t.reshape(2,60)   # Matrix mit 2 Zeilen, 60 Spalten  
t.reshape(60,2)   # Matrix mit 60 Zeilen, 2 Spalten
t.reshape(2,3,20) # 2 Matrizen mit je 3 Zeilen und 20 Spalten hintereinander gestapelt
t.reshape(2,3,20)[1][2][17]

tensor(117)

In [49]:
t.reshape(2,3,4,5)[1][1][2][3]  # 2 Quader, bestehend aus 3 hintereinandergestapelten 4x5 Matrizen  

tensor(93)

In [43]:
t.reshape(2,4,3,5)[1][1][2][3] # 2 Quader, bestehend aus 4 hintereinandergestapelten 3x5 Matrizen   

tensor(88)

<img src="./img/nn-reshape.png" width="800"/>    