## Pytorch



In [2]:
import torch
import torch.optim as optim
import torch.nn.functional as F
import torch.nn as nn
import numpy as np

#### OR-Funktion

Ein Netz, bestehend aus einem Neuron mit Sigmoid-Aktivierung 


In [3]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,1)
 
    def forward(self, t):
        t = self.fc1(t)
        t = torch.sigmoid(t)
        return t

In [4]:
net = Net()
x = torch.Tensor([[0,0],[0,1],[1,0],[1,1]]).reshape(4,1,2)
labels = torch.Tensor([0,1,1,1]).reshape(4,1,1)

optimizer = optim.SGD(net.parameters(), lr=0.1)
loss_fn = torch.nn.MSELoss(reduction='mean')

for epoch in range(2000):
        outputs = net(x)
        loss = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
            
net(x)

tensor([[[0.2062]],

        [[0.8756]],

        [[0.8787]],

        [[0.9949]]], grad_fn=<SigmoidBackward>)

#### XOR-Funktion

Bei zwei Neuronen im hidden-Layer kann man schon mal Pech haben. Aber bei drei klappt es meistens. 

In [5]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,3)
        self.fc2 = nn.Linear(3,1)
 
    def forward(self, t):
        t = self.fc1(t)
        t = torch.relu(t)
        t = self.fc2(t)
        t = torch.sigmoid(t)
        return t

In [6]:
net = Net()
x = torch.Tensor([[0,0],[0,1],[1,0],[1,1]]).reshape(4,1,2)
labels = torch.Tensor([0,1,1,0]).reshape(4,1,1)

#optimizer = optim.Adam(net.parameters(), lr=0.01)
#optimizer = optim.RMSprop(net.parameters(), lr=0.01)
optimizer = optim.SGD(net.parameters(), lr=0.01)
loss_fn = torch.nn.MSELoss(reduction='mean')

for epoch in range(20000):
        outputs = net(x)
        loss = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

net(x)

tensor([[[0.0679]],

        [[0.6586]],

        [[0.6586]],

        [[0.6586]]], grad_fn=<SigmoidBackward>)

Wir experimentieren mit weiteren Layern, verschiedenen learning rates, verschiedenen Optimizern

In [7]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2,16)
        self.fc2 = nn.Linear(16,8)
        self.fc3 = nn.Linear(8,1)
 
    def forward(self, t):
        t = self.fc1(t)
        t = torch.relu(t)
        t = self.fc2(t)
        t = torch.relu(t)
        t = self.fc3(t)
        t = torch.sigmoid(t)
        return t

In [8]:
net = Net()
x = torch.Tensor([[0,0],[0,1],[1,0],[1,1]]).reshape(4,1,2)
labels = torch.Tensor([0,1,1,0]).reshape(4,1,1)

#optimizer = optim.Adam(net.parameters(), lr=0.01)
#optimizer = optim.RMSprop(net.parameters(), lr=0.01)
optimizer = optim.SGD(net.parameters(), lr=0.05)
loss_fn = torch.nn.MSELoss(reduction='mean')

for epoch in range(5000):
        outputs = net(x)
        loss = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

net(x)

tensor([[[0.0262]],

        [[0.9854]],

        [[0.9787]],

        [[0.0143]]], grad_fn=<SigmoidBackward>)