[docs](https://pytorch.org/docs/stable/torch.html)

In [1]:
from __future__ import print_function
import torch

Eine nicht initialisierte Matrix enthält die Werte, die gerade gespeichert sind.

In [ ]:
x = torch.empty(5, 3)
print(x)

Eine Matrix mit Zufallswerten

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4006, 0.6970, 0.0119],
        [0.5101, 0.0446, 0.2879],
        [0.7836, 0.1944, 0.2797],
        [0.1717, 0.8870, 0.1926],
        [0.7924, 0.7176, 0.3135]])


Eine Matrix, die nur Nullen vom Typ long enthält

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Einen Tensor aus einer Liste erstellen

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Einen neuen Tensor aus einem bestehenden erzeugen:

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2930, -0.0279,  0.0578],
        [ 1.0888, -1.1141, -0.2588],
        [ 0.5320, -0.2677,  0.7996],
        [ 0.2228,  0.0243, -0.5558],
        [ 1.4573,  2.0228,  0.7705]])


In [8]:
print(x.size())

torch.Size([5, 3])


#### Operations

Mehrere Möglichkeiten für die Addition

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8627,  0.5773,  0.2918],
        [ 1.5745, -0.5290, -0.0254],
        [ 0.5829,  0.4363,  1.3592],
        [ 0.8491,  1.0156, -0.0137],
        [ 1.9207,  2.6880,  1.6634]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.8627,  0.5773,  0.2918],
        [ 1.5745, -0.5290, -0.0254],
        [ 0.5829,  0.4363,  1.3592],
        [ 0.8491,  1.0156, -0.0137],
        [ 1.9207,  2.6880,  1.6634]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8627,  0.5773,  0.2918],
        [ 1.5745, -0.5290, -0.0254],
        [ 0.5829,  0.4363,  1.3592],
        [ 0.8491,  1.0156, -0.0137],
        [ 1.9207,  2.6880,  1.6634]])


In [12]:
# Addition in-place
y.add_(x)
print(y)

tensor([[ 0.8627,  0.5773,  0.2918],
        [ 1.5745, -0.5290, -0.0254],
        [ 0.5829,  0.4363,  1.3592],
        [ 0.8491,  1.0156, -0.0137],
        [ 1.9207,  2.6880,  1.6634]])


Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x. 

You can use standard NumPy-like indexing with all bells and whistles!

In [14]:
print(x)
print(x[:, 1])

tensor([[ 0.2930, -0.0279,  0.0578],
        [ 1.0888, -1.1141, -0.2588],
        [ 0.5320, -0.2677,  0.7996],
        [ 0.2228,  0.0243, -0.5558],
        [ 1.4573,  2.0228,  0.7705]])
tensor([-0.0279, -1.1141, -0.2677,  0.0243,  2.0228])


Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
print(y)
print(z)

tensor([ 2.1325, -0.0528,  0.6703,  0.1820, -0.8494, -1.0934,  0.9514, -2.0207,
        -1.5418, -1.2959,  0.4523, -1.1169,  0.5587,  0.9782, -0.5198, -1.2031])
tensor([[ 2.1325, -0.0528,  0.6703,  0.1820, -0.8494, -1.0934,  0.9514, -2.0207],
        [-1.5418, -1.2959,  0.4523, -1.1169,  0.5587,  0.9782, -0.5198, -1.2031]])


If you have a one element tensor, use .item() to get the value as a Python number

In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9093])
-0.9093368649482727


#### Numpy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [18]:
a = torch.ones(5)
b = a.numpy()
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [2]:
help(torch.argmin)

Help on built-in function argmin:

argmin(...)
    .. function:: argmin(input) -> LongTensor
    
    Returns the indices of the minimum value of all elements in the :attr:`input` tensor.
    
    This is the second value returned by :meth:`torch.min`. See its
    documentation for the exact semantics of this method.
    
    Args:
        input (Tensor): the input tensor.
    
    Example::
    
        >>> a = torch.randn(4, 4)
        >>> a
        tensor([[ 0.1139,  0.2254, -0.1381,  0.3687],
                [ 1.0100, -1.1975, -0.0102, -0.4732],
                [-0.9240,  0.1207, -0.7506, -1.0213],
                [ 1.7809, -1.2960,  0.9384,  0.1438]])
        >>> torch.argmin(a)
        tensor(13)
    
    .. function:: argmin(input, dim, keepdim=False, out=None) -> LongTensor
    
    Returns the indices of the minimum values of a tensor across a dimension.
    
    This is the second value returned by :meth:`torch.min`. See its
    documentation for the exact semantics of this m

In [19]:
x = torch.Tensor([
    [[0,1],[2,3]],
    [[4,5],[6,7]],
    [[8,9],[10,11]]
])

In [20]:
x.shape

torch.Size([3, 2, 2])

In [21]:
for k in range(3):
    print(x[k])

tensor([[0., 1.],
        [2., 3.]])
tensor([[4., 5.],
        [6., 7.]])
tensor([[ 8.,  9.],
        [10., 11.]])


In [22]:
x1 = x.reshape(2,2,3)

In [26]:
y = torch.Tensor(2,2,3)
for i in range(2):
    for j in range(2):
        y[i][j][0] = x[0][i][j]
    
    
for i in range(2):
    for j in range(2):
        y[i][j][1] = x[1][i][j]
for i in range(2):
    for j in range(2):
        y[i][j][2] = x[2][i][j]

In [27]:
y

tensor([[[ 0.,  4.,  8.],
         [ 1.,  5.,  9.]],

        [[ 2.,  6., 10.],
         [ 3.,  7., 11.]]])

In [18]:
for i in range(2):
    for j in range(2):
        print(y[i][j][2])

tensor(2.)
tensor(2.)
tensor(2.)
tensor(2.)
