In [2]:
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import numpy as np
torch.set_printoptions(linewidth=120)

In [31]:
class Perceptron(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(in_features=2, out_features=1)
        self.fc1.weight.data = torch.tensor([[3.0, 1.0]])
        self.fc1.bias.data = torch.tensor([2.0])
            
    def forward(self, t):
        t = self.fc1(t)
        return t
    
p = Perceptron()
x = torch.tensor([3., 2.])
p(x)

tensor([13.], grad_fn=<AddBackward0>)

In [49]:
class Neuron(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(in_features=2, out_features=1)
        self.fc1.weight.data = torch.tensor([[3.0, 1.0]])
        self.fc1.bias.data = torch.tensor([2.0])
            
    def forward(self, t):
        t = self.fc1(t)
        t = torch.sigmoid(t)
        return t
    
p = Neuron()
x = torch.tensor([[0,0],[0,1],[1,0],[1,1]]).float()
p(x)
 

tensor([[0.8808],
        [0.9526],
        [0.9933],
        [0.9975]], grad_fn=<SigmoidBackward>)

In [37]:
t = torch.Tensor([3,4])

In [38]:
net(t)

tensor([15.], grad_fn=<AddBackward0>)

In [39]:
t = torch.Tensor([[3,4],[1,2],[2,2]])
t.shape

torch.Size([3, 2])

In [41]:
net(t)

tensor([[15.],
        [ 7.],
        [10.]], grad_fn=<AddmmBackward>)

In [4]:
class Netz2P(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(in_features=2, out_features=2)
        self.fc1.weight.data = torch.tensor([[3.0, 1.0],[2.0, -1.0]])
        self.fc1.bias.data = torch.tensor([1.0,2.0])
        self.fc2 = nn.Linear(in_features=2, out_features=1)
        self.fc2.weight.data = torch.tensor([[1.0, -1.0]])
        self.fc2.bias.data = torch.tensor([-2.0])
            
    def forward(self, t):
        t = self.fc1(t)
        t = torch.relu(t)
        t = self.fc2(t)
        t = torch.sigmoid(t)
        return t
    
net = Netz2P()
x = torch.tensor([3., 2.])
net(x)

tensor([0.9820], grad_fn=<SigmoidBackward>)

In [68]:
class Netz2(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(in_features=2, out_features=3)
        self.fc1.weight.data = torch.tensor([[3.0, 1.0],[2.0, -1.0],[-1,2]])
        self.fc1.bias.data = torch.tensor([1.0,2.0,1.0])
        self.fc2 = nn.Linear(in_features=3, out_features=1)
        self.fc2.weight.data = torch.tensor([[-1.0, 2.0, 3.0]])
        self.fc2.bias.data = torch.tensor([-1.0])
            
    def forward(self, t):
        t = self.fc1(t)
        t = torch.relu(t)
        t = self.fc2(t)
        t = torch.sigmoid(t)
        return t
    
net = Netz2()
#x = torch.tensor([[3., 2.],[1.,2.],[-1.,1],[0,2]])
x = torch.tensor([2.,1.])
net(x)


target = torch.tensor([0])
loss = abs(target-net(x))
loss.backward()
print(net.fc1.weight.grad)


tensor([[-0.0353, -0.0177],
        [ 0.0707,  0.0353],
        [ 0.1060,  0.0530]])


In [20]:
class Netz3(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(in_features=2, out_features=2)
        self.fc1.weight.data = torch.tensor([[3.0, 1.0],[2.0, -1.0]])
        self.fc1.bias.data = torch.tensor([1.0,2.0])
        self.fc2 = nn.Linear(in_features=2, out_features=1)
        self.fc2.weight.data = torch.tensor([[-1.0, 2.0]])
        self.fc2.bias.data = torch.tensor([-1.0])
            
    def forward(self, t):
        t = self.fc1(t)
        t = torch.relu(t)
        print(t)
        t = self.fc2(t)
        print(t)
        t = torch.sigmoid(t)
        
        return t
    
net = Netz3()
#x = torch.tensor([[3., 2.],[1.,2.],[-1.,1],[0,2]])
x = torch.tensor([2.,1.])
net(x)


target = torch.tensor([0])
loss = 0.5*(target-net(x))**2
loss.backward()
print(net.fc1.weight.grad)
print(net.fc2.bias.grad)
print(net.fc2.weight.grad)

tensor([8., 5.], grad_fn=<ReluBackward0>)
tensor([1.], grad_fn=<AddBackward0>)
tensor([8., 5.], grad_fn=<ReluBackward0>)
tensor([1.], grad_fn=<AddBackward0>)
tensor([[-0.2875, -0.1437],
        [ 0.5749,  0.2875]])
tensor([0.1437])
tensor([[1.1499, 0.7187]])


In [11]:
import math
def sigmoid(x):
    return  1/(1+math.exp(-1.0*x))

In [76]:
# Ergebnis von oben nachrechnen
w1, b1 = np.array([3,1]), 1
w2, b2 = np.array([2,-1]), 2
w3, b3 = np.array([-1,2]), -1
x1, x2 = 2, 1
y = 0
    
W = np.array([w1,w2])   
x = np.array([x1,x2]).T
b = np.array([b1,b2]).T
z = np.dot(W,x)+ b
a = torch.relu(torch.tensor(z)).numpy()
z3 = np.dot(w3,a)+b3
a3 = sigmoid(z3)
dloss = a3-y
db3 = a3*(1-a3)*dloss
dw3 = a * db3
print("n3: ",dw3,db3)
db1 = 0 if a[0] <= 0 else 1
db2 = 0 if a[1] <= 0 else 1
dw1 = x * db1*db3*w3[0]
dw2 = x * db2*db3*w3[1]
print("n1: ",dw1,db1)
print("n2: ",dw2,db2)

n3:  [1.14987872 0.7186742 ] 0.14373484045721513
n1:  [-0.28746968 -0.14373484] 1
n2:  [0.57493936 0.28746968] 1
