In [1]:
import numpy as np

In [41]:
tn = [7,10,14,16,18,19,20,24,26,29,30,32]
#tn = [7,10,14,16,18,19,20]
 

# inf = 10000
# tn = [-inf] + tn + [inf]
# al = [-inf] + al + [inf]

N = len(tn)
m = 5      # Anzahl der Zahlen, die Al wählen darf

Zur Kontrolle wird für kleine Eingaben ein brute-force Ergebnis berechnet.

In [42]:
def minAbstand(x,al):
    '''returns minimaler Abstand von x zu einer Zahl in al'''
    minabs = abs(x-al[0])
    for y in al:
        if abs(x-y) < minabs:
            minabs = abs(x-y)
    return minabs

def sumKosten(tn,al):
    '''summe der Kosten wenn al die gewählten Zahlen sind'''
    summe = 0
    for x in tn:
        summe+=minAbstand(x,al)
    return summe
        
print(sumKosten(tn,[7,10,14]))

88


In [47]:
from itertools import *
inf = float('inf')

tn = [7,10,14,16,18,19,20,24,26,29,30,32]
minKost = inf
minA    = None
for a in combinations(tn,5):
    if sumKosten(tn,a) < minKost:
        minKost = sumKosten(tn,a)
        minA = a

print(minKost, minA)

12 (7, 14, 19, 24, 30)


In [44]:
def abschnitt(i,k):
    '''
    Kosten für i-k, wenn nur k gewählt wurde
    '''
    kosten = 0
    for k in range(i,k):
        kosten += abs(tn[i]-tn[k]) 
    return kosten

In [45]:
'''
a[m,i,j] = Kosten für i-j, wenn höchstens m Zahlen in i-j gewählt werden dürfen.

a[1,i,j] = Kosten für i-j, wenn genau eine Zahl in i-j gewählt werden darf.

'''



import numpy as np
a = np.zeros((m,N,N),dtype='uint32')
 

In [51]:
def kosten1(i,j):
    ''' Kosten für i-j, wenn höchstens eine Zahl in i-j gewählt werden darf'''
    minKosten = 10000
    minK = -1
    
    for k in range(i,j+1):
        if einzelKosten(i,j,k) < minKosten:
            minKosten = einzelKosten(i,j,k)
            minK = k
    return minKosten, minK

def einzelKosten(i,j,k):
    '''Kosten für i-j, wenn man k wählt'''
    summe = 0
    for s in range(i,j+1):
        summe += abs(tn[s]-tn[k])
    return summe
        
print(kosten1(0,3))

for i in range(N):
    for j in range(N):
        if i<=j:
            
            a[0,i,j],_=kosten1(i,j)
            

for s in range(1,m):
    for i in range(N):
        for j in range(N):
            if i<=j:
                a[s,i,j]=a[s-1,i,j]
                for k in range(i,j+1):
                    if abschnitt(i,k)+a[s-1,k,j] < a[s,i,j]:
                        a[s,i,j]= abschnitt(i,k)+a[s-1,k,j]
a      

(13, 1)


array([[[ 0,  3,  7, 13, 17, 22, 26],
        [ 0,  0,  4,  6, 10, 13, 17],
        [ 0,  0,  0,  2,  4,  7,  9],
        [ 0,  0,  0,  0,  2,  3,  5],
        [ 0,  0,  0,  0,  0,  1,  2],
        [ 0,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  3,  5,  7, 10, 12],
        [ 0,  0,  0,  2,  4,  7,  9],
        [ 0,  0,  0,  0,  2,  3,  4],
        [ 0,  0,  0,  0,  0,  1,  2],
        [ 0,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  2,  4,  6,  7],
        [ 0,  0,  0,  0,  2,  3,  4],
        [ 0,  0,  0,  0,  0,  1,  2],
        [ 0,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0]]], dtype=uint32)

Beispiel:

In [58]:
a =  np.zeros((3,5),dtype='uint32') 
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint32)

In [67]:
a[1,:]

array([0, 0, 0, 0, 0], dtype=uint32)

#### Tabelle kosten

**loesung(i,l)** = optimale Lösung für Teilnehmer ab Index i bei l Zahlen (zusätzlich zu den Randzahlen)

**kosten(i,l)** = minimale Auszahlung an die Teilnehmer ab Index i , wenn man l ihrer Zahlen wählen darf (ausser den Randzahlen) 

z.B. kosten(2,0) sind die Auszahlungskosten für die Teilnehmer ab Index 2, wenn man außer den Randwerten 2 und N-1, keine sonstigen Zahlen nehmen darf.

In [120]:
kosten = np.zeros((N,m),dtype='uint32') 
loesung = np.zeros((N,m),dtype='uint32') 
for i in range(N):
    kosten[i,0]=kostenabschnitt[i,N-1]
 


In [121]:
kosten[2,0], kosten[4,0]

(37, 9)

In [7]:
a = np.random.randn(5) 
 
a

array([ 0.75624725, -1.20223758, -1.65594827,  0.19670773, -1.42712483])

In [12]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a = np.full((2,2),' ')
a

array([[' ', ' '],
       [' ', ' ']], dtype='<U1')

In [20]:
from itertools import *
list(combinations('ABCD', 2))  
a = [3, 4, 7, 9]
for x,y in combinations(a,2):
    print(x,y)


3 4
3 7
3 9
4 7
4 9
7 9
